ALTER TABLE task 
ADD COLUMN IF NOT EXISTS startable BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE task 
ADD COLUMN IF NOT EXISTS parent_success INT4 NOT NULL DEFAULT 0;

ALTER TABLE task 
ADD COLUMN IF NOT EXISTS parent_failures INT4 NOT NULL DEFAULT 0;